### ISSUE TITLE
main.js

### ISSUE THREAD

**Issue by nadajames** [skorulis/beermoney-balances#1]
https://github.com/skorulis/beermoney-balances/blob/7e0d5399b94a46a2299d1f04418cb064e320c260/manifest.json#L25

It seems broad to insert jQuery and the main.js file into every page. Not a security risk, since content scripts are sandboxed, but it is added overhead on each page load.

Are we missing something?

**Comment by skorulis** [comment]
Simply a matter of choosing code conciseness over performance. I'll add the common scripts to each entry and get rid of the catch all to correct this

**Comment by skorulis** [comment]
Fixed in ad8515f80bf31219489c88110e7e0a9426c93d30
