### ISSUE TITLE
Checkpoints page display unreliable

### ISSUE THREAD

**Issue by rsarvas** [skorulis/beermoney-balances#6]
The trailing slash in the checkpoints entry of the "meta.json"causes issues loading the Checkpoints status page reliably. Removing the trailing slash resolves the issue.

`	"checkpoints": {
		"conversion": 335,
		"url":"http://www.checkpoints.com/collect",
		"name":"CheckPoints",
		"fractions":false
	},`

**Comment by skorulis** [comment]
Fixed in 89593fcffe8bd7e9dcab0c9f55fa7ae70f1ad4e7
